# Generated by Django 6.0.1 on 2026-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('view_count', models.CharField(blank=True, max_length=50, null=True)),
                ('poster', models.URLField(max_length=1000)),
                ('backdrop', models.URLField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(max_length=100)),
                ('is_hero', models.BooleanField(default=False)),
            ],
        ),
    ]
